### PR TITLE
fix : Remove boxes till you reach the main screen

### PR DESCRIPTION
**Pull request by surajondev**
I have added style features and modified game.js such that the border of the boxes are not displayed till the submission of the pokemon. 

You can have a look

Regards
- Suraj

### CODE REVIEW

**Comment by narenbakshi97** [comment]
Thanks Suraj, 
I am merging your pull request, next time make sure to first get the issue assigned to you before creating a pull request, it helps to avoid multiple people working on the same issue, nevertheless, thanks for your contribution, feel free to go through other issues

**Comment by surajondev** [comment]
Thank you so much.

I am a bit new to contributing to open source and learning it. 
So next time I take care of it.

**Comment by narenbakshi97** [comment]
No worries bud! 

[TIP]: In every Github repo you will find a file named CONTRIBUTION.md with all the rules and how-tos for contributors

Happy coding!

**Comment by surajondev** [comment]
Thank you for the tip.

Looking forward to solving more issues.

**Pull request merged**
